# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170429_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
    ]
