# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='user-default.png', upload_to='media'),
        ),
    ]
