# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170504_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='user_default.png', upload_to='media'),
        ),
    ]
