# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170505_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/user_default.png', upload_to='media'),
        ),
    ]
