# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$', max_length=3),
        ),
    ]
