# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170406_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
